### ISSUE TITLE
Support for non-required Id

### ISSUE THREAD

**Issue by mad** [microsoft/spring-data-gremlin#142]
JanusGraph doesn't support clean user defined ID. It uses own layout for internal id, and generate internally

Some features that graph support may be retrieved from http://tinkerpop.apache.org/javadocs/3.3.3/core/org/apache/tinkerpop/gremlin/structure/Graph.Features.ElementFeatures.html#supportsUserSuppliedIds

**Comment by fabiencoppens** [comment]
It looks like JanusGraph 0.3.0 has an option to let users supply ids as longs, but it is not recommended, based on their documentation. It is a config setting that has to be configured when the backing datastore is initialized, and cannot be changed afterward. The config flag is `graph.set-vertex-id` 
See here: https://docs.janusgraph.org/latest/config-ref.html#_graph.
The doc says: "Whether user provided vertex ids should be enabled and JanusGraph’s automatic id allocation be disabled. Useful when operating JanusGraph in concert with another storage system that assigns long ids but disables some of JanusGraph’s advanced features which can lead to inconsistent data. EXPERT FEATURE - USE WITH GREAT CARE."

I agree though that it would be better to rely on JanusGraph's internally generated ids.

**Comment by fabiencoppens** [comment]
@Incarnation-p-lee I pushed a PR to make ids optional [PR #155 ](https://github.com/Microsoft/spring-data-gremlin/pull/155)

**Comment by nefkor** [comment]
Hi, is this feature not available yet?

**Comment by rekon** [comment]
Hi, I am using Gremlin Server hosting **Neo4j**. Since Neo4j doesn't require **id**s to be explicitly specified by its nodes(or vertices) therefore when I run the example I get the following error -

> _org.springframework.beans.factory.BeanCreationException_: Error creating bean with name 'application': Invocation of init method
failed; nested exception is com.microsoft.spring.data.gremlin.exception.GremlinQueryException: unable to complete query from gremlin; nested exception is java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: **Vertex does not support user supplied identifiers**

And when I use **@GeneratedValue** with **@ Id**, and don't pass **id** in constructor of Person class, I get the following error -

> _org.springframework.beans.factory.BeanCreationException_: Error creating bean with name 'application': Invocation of init method failed; nested exception is com.microsoft.spring.data.gremlin.exception.GremlinInvalidEntityIdFieldException: **The vertex id for the from vertex cannot be null**!

Please help

**Comment by Tin-Nguyen** [comment]
hi @rekon , did you resolve your issue yet? I get the same issue as yours and looking for a solution to resolve it now.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
