### ISSUE TITLE
Support @Link or @ManyToOne equivalent

### ISSUE THREAD

**Issue by anthony-o** [microsoft/spring-data-gremlin#189]
I would need a way to add inside a `@Vertex` object a field pointing to another `@Vertex` which would be the entity that can be retrieved via an `@Edge` whose label is the name of the object field.

https://github.com/zifnab87/spring-data-gremlin implement this via a `@Link` annotation.

Example:
```java
@Vertex
public class Person {
    @Id
    private String id;

    @Link("livesAt")
    private Address address;

    @Link
    private Address defaultShipTo;
}

@Vertex
public class Address {
    @Id
    private String id;

    private String city;

    private String street;
}
```
Here a `Person` will retrieve a vertex `Address` via an edge labelled "livesAt" and another vertex `Address` via an edge labelled "defaultShipTo" into respective fields.

**Comment by Incarnation-p-lee** [comment]
@anthony-o 
Thanks for your effort and issue, the feature may looks like gremlin syntax such as
```gremlin
g.V().has(id, xxx).OutE()
```
But some details may need to investigate about this annotation, one most important thing about this is the graph modification. Consider one simple scenario here, assume we have one Vertex Person and two Vertex Address in graph, "liveAt" point to Address A and "defaultShipTo" point to Address B. It should works well with the annotation here. Now if the person got a new address with label "livesAt", and create a new Edge from person to the new Address, do we need to update the class struct for Person ? or what happens if we retrieve instance from backend DB to java instance ?

I am not well consideration about this and will take some effort to investigation.

**Comment by kai18** [comment]
Is there an update or a timeline on this feature?

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
